#! /usr/bin/env python3
"""HOMEINFO news daemon."""

from hinews.config import CONFIG
from hinews.wsgi import APPLICATION


if __name__ == '__main__':
    HOST = CONFIG['wsgi']['host']
    PORT = int(CONFIG['wsgi']['port'])
    APPLICATION.run(host=HOST, port=PORT)
